apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/whitelist-source-range: '165.0.108.101'
    #nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/proxy-body-size: "0"
    #nginx.org/client-max-body-size: "500m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # UPDATE THIS LINE ABOVE
spec:
  rules:
    - http:
        paths:
          - path: /
            # UPDATE THIS LINE ABOVE
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 80
          - path: /phpmyadmin/
            # UPDATE THIS LINE ABOVE
            backend:
              serviceName: phpmyadmin-cluster-ip-service
              servicePort: 80
